// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "readable_id", Type: field.TypeUUID},
		{Name: "media_type", Type: field.TypeEnum, Enums: []string{"IMAGE", "VIDEO"}},
		{Name: "project_id", Type: field.TypeString},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaTable,
	}
)

func init() {
}
